Repository Keyneez/Keyneez-AOS-Release, pull requests merged in 2023-04, with the labels that each got.

#9 [ADD/#5] font 및 color 추가
  app/src/main/java/com/release/keyneez/MainActivity.kt
  app/src/main/res/font/keyneez_font.xml
  app/src/main/res/font/pretendard_bold.otf
  app/src/main/res/font/pretendard_medium.otf
  app/src/main/res/font/pretendard_semibold.otf
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/styles.xml
  app/src/main/res/values/themes.xml
Labels: ADD ➕, Pull Request 🤗, 채연 🐸

#11 [UI/#2] search / 검색 뷰 구현
  app/src/main/res/drawable/ic_search_back.xml
  app/src/main/res/drawable/ic_search_blue.png
  app/src/main/res/drawable/ic_search_empty_heart.xml
  app/src/main/res/drawable/ic_search_full_heart.xml
  app/src/main/res/drawable/ic_search_red.png
  app/src/main/res/drawable/ic_search_search.xml
  app/src/main/res/drawable/img_search_background.png
  app/src/main/res/drawable/sel_search_heart.xml
  app/src/main/res/drawable/sel_search_icon.xml
  app/src/main/res/drawable/shape_gray400_bottomline_rect.xml
  app/src/main/res/layout/activity_search.xml
  app/src/main/res/layout/item_search_content.xml
  app/src/main/res/values/strings.xml
Labels: Pull Request 🤗, UI 💄, 지은 🐭

#13 [CHORE/#12] 기초 세팅
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/release/keyneez/presentation/main/MainActivity.kt
  app/src/main/java/com/release/keyneez/util/DiffCallback.kt
  app/src/main/java/com/release/keyneez/util/OnSingleClickListener.kt
  app/src/main/java/com/release/keyneez/util/UiState.kt
  app/src/main/java/com/release/keyneez/util/binding/BindingActivity.kt
  app/src/main/java/com/release/keyneez/util/binding/BindingFragment.kt
  app/src/main/java/com/release/keyneez/util/extension/ActivityExt.kt
  app/src/main/java/com/release/keyneez/util/extension/ContextExt.kt
  app/src/main/java/com/release/keyneez/util/extension/MutableLiveDataExt.kt
  app/src/main/java/com/release/keyneez/util/extension/ViewExt.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/values/strings.xml
Labels: CHORE 🎀, Pull Request 🤗, 지은 🐭
